### ISSUE TITLE
No issue, this lib is awesome

### ISSUE THREAD

**Issue by MarcoWorms** [grrr-amsterdam/garp-functional#1]
I recently moved to PHP from JS at my work and I was searching for something like https://github.com/ramda/ramda

Thanks a lot for this, your lib has the best usage and UX from all the functional libs I saw until now

Don't let this die, I'll use it a lot and will try to open a PR if i find something to add here :D

**Comment by harmenjanssen** [comment]
Wow, that's so good to hear! Thanks for your comment.  
I have absolutely no intention of letting this die :)
