### ISSUE TITLE
v1.0.5 tag is not prefixed with `v`

### ISSUE THREAD

**Issue by MarcoWorms** [grrr-amsterdam/garp-functional#4]
So, I saw the tags had a `v` prefix but 1.0.5 doesn't. I don't think it's really a problem but it's an inconsistency :)

**Comment by harmenjanssen** [comment]
You're right! Thanks, I renamed the tag.

I started trying out [this new git branching model](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow) last night and lost some automation in the process.  

Thanks for the heads up!
